# -*- coding: utf-8 -*-
"""app real estate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ti3dfcg0dgOY0VbBiB2u5uRjxsRHuy7R
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# ---------------- PAGE CONFIG ----------------
st.set_page_config(page_title="Real Estate EDA Dashboard", layout="wide")
st.title("Real Estate Exploratory Data Analysis")

# ---------------- FILE PATH ----------------
INPUT_PATH = "india_housing_prices.csv.gz"

# ---------------- LOAD DATA ----------------
@st.cache_data
def load_data():
    return pd.read_csv(INPUT_PATH)

df = load_data()

st.subheader("Dataset Overview")
st.write("Shape:", df.shape)
st.write("Columns:", list(df.columns))

# ---------------- DATA CLEANING ----------------
for col in df.select_dtypes(include="object"):
    df[col] = df[col].astype(str).str.strip().replace("nan", np.nan)

numeric_cols = [
    "BHK", "Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt",
    "Year_Built", "Floor_No", "Total_Floors",
    "Age_of_Property", "Nearby_Schools", "Nearby_Hospitals",
    "Public_Transport_Accessibility", "Parking_Space"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# ---------------- FEATURE ENGINEERING ----------------
if {"Price_in_Lakhs", "Size_in_SqFt"}.issubset(df.columns):
    df["Price_Rs"] = df["Price_in_Lakhs"] * 100000
    df["Price_per_SqFt"] = df["Price_Rs"] / df["Size_in_SqFt"]

CURRENT_YEAR = 2025
if "Year_Built" in df.columns:
    df["Age_of_Property"] = df["Age_of_Property"].fillna(
        CURRENT_YEAR - df["Year_Built"]
    )

# ---------------- HANDLE MISSING VALUES ----------------
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include="object"):
    df[col] = df[col].fillna("Unknown")

df = df.drop_duplicates()

# ---------------- SUMMARY ----------------
st.subheader("Statistical Summary")
st.dataframe(df.describe())

# ================= UNIVARIATE ANALYSIS =================
st.header("Univariate Analysis")

fig, ax = plt.subplots()
sns.histplot(df["Price_in_Lakhs"], bins=40, kde=True, ax=ax)
ax.set_title("Price Distribution (Lakhs)")
st.pyplot(fig)
plt.close(fig)

fig, ax = plt.subplots()
sns.histplot(df["Size_in_SqFt"], bins=40, kde=True, ax=ax)
ax.set_title("Size Distribution (SqFt)")
st.pyplot(fig)
plt.close(fig)

fig, ax = plt.subplots()
sns.histplot(df["Price_per_SqFt"], bins=40, kde=True, ax=ax)
ax.set_title("Price per SqFt Distribution")
st.pyplot(fig)
plt.close(fig)

# ================= BIVARIATE ANALYSIS =================
st.header("Bivariate Analysis")

fig, ax = plt.subplots()
sns.scatterplot(
    x=df["Size_in_SqFt"],
    y=df["Price_in_Lakhs"],
    alpha=0.4,
    ax=ax
)
ax.set_title("Size vs Price")
st.pyplot(fig)
plt.close(fig)

if "City" in df.columns:
    city_avg = (
        df.groupby("City")["Price_in_Lakhs"]
        .mean()
        .sort_values(ascending=False)
        .head(10)
    )

    fig, ax = plt.subplots(figsize=(10, 4))
    sns.barplot(x=city_avg.index, y=city_avg.values, ax=ax)
    ax.set_title("Average Property Price by City (Top 10)")
    ax.tick_params(axis="x", rotation=45)
    st.pyplot(fig)
    plt.close(fig)

if "Property_Type" in df.columns:
    fig, ax = plt.subplots(figsize=(8, 4))
    sns.boxplot(
        data=df,
        x="Property_Type",
        y="Price_per_SqFt",
        ax=ax
    )
    ax.set_title("Price per SqFt by Property Type")
    ax.tick_params(axis="x", rotation=45)
    st.pyplot(fig)
    plt.close(fig)

# ================= CORRELATION =================
st.header("Correlation Heatmap")

fig, ax = plt.subplots(figsize=(10, 5))
sns.heatmap(
    df.select_dtypes(include=np.number).corr(),
    cmap="coolwarm",
    ax=ax
)
st.pyplot(fig)
plt.close(fig)

# ================= TOP LOCALITIES =================
if "Locality" in df.columns:
    st.header("Top 10 Most Expensive Localities")

    top_local = (
        df.groupby("Locality")["Price_per_SqFt"]
        .mean()
        .sort_values(ascending=False)
        .head(10)
    )

    fig, ax = plt.subplots(figsize=(10, 4))
    sns.barplot(x=top_local.index, y=top_local.values, ax=ax)
    ax.set_title("Top 10 Expensive Localities (Price/SqFt)")
    ax.tick_params(axis="x", rotation=45)
    st.pyplot(fig)
    plt.close(fig)

st.success("EDA Completed Successfully")