# -*- coding: utf-8 -*-
"""real-estate_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xLU64bUxinU-PU_ymwTLGDz2uueT58nT
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import warnings
warnings.filterwarnings("ignore")

# ---------------- PAGE CONFIG ----------------
st.set_page_config(page_title="Real Estate EDA Dashboard", layout="wide")
st.title("Real Estate Exploratory Data Analysis")

alt.data_transformers.disable_max_rows()

# ---------------- FILE PATH ----------------
INPUT_PATH = "india_housing_prices.csv.gz"

# ---------------- LOAD DATA ----------------
@st.cache_data
def load_data():
    return pd.read_csv(INPUT_PATH)

df = load_data()

st.subheader("Dataset Overview")
st.write("Shape:", df.shape)
st.write("Columns:", list(df.columns))

# ---------------- DATA CLEANING ----------------
for col in df.select_dtypes(include="object"):
    df[col] = df[col].astype(str).str.strip().replace("nan", np.nan)

numeric_cols = [
    "BHK", "Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt",
    "Year_Built", "Floor_No", "Total_Floors",
    "Age_of_Property", "Nearby_Schools", "Nearby_Hospitals",
    "Public_Transport_Accessibility", "Parking_Space"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# ---------------- FEATURE ENGINEERING ----------------
if {"Price_in_Lakhs", "Size_in_SqFt"}.issubset(df.columns):
    df["Price_Rs"] = df["Price_in_Lakhs"] * 100000
    df["Price_per_SqFt"] = df["Price_Rs"] / df["Size_in_SqFt"]

CURRENT_YEAR = 2025
if "Year_Built" in df.columns:
    df["Age_of_Property"] = df["Age_of_Property"].fillna(
        CURRENT_YEAR - df["Year_Built"]
    )

# ---------------- HANDLE MISSING VALUES ----------------
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include="object"):
    df[col] = df[col].fillna("Unknown")

df = df.drop_duplicates()

# ---------------- SUMMARY ----------------
st.subheader("Statistical Summary")
st.dataframe(df.describe())

# ================= UNIVARIATE ANALYSIS =================
st.header("Univariate Analysis")

# Price Distribution
price_hist = alt.Chart(df).mark_bar().encode(
    x=alt.X("Price_in_Lakhs:Q", bin=alt.Bin(maxbins=40), title="Price (Lakhs)"),
    y=alt.Y("count():Q"),
    tooltip=["count():Q"]
).properties(title="Price Distribution (Lakhs)")

st.altair_chart(price_hist, width='stretch')

# Size Distribution
size_hist = alt.Chart(df).mark_bar().encode(
    x=alt.X("Size_in_SqFt:Q", bin=alt.Bin(maxbins=40), title="Size (SqFt)"),
    y="count():Q",
    tooltip=["count():Q"]
).properties(title="Size Distribution (SqFt)")

st.altair_chart(size_hist, width='stretch')

# Price per SqFt Distribution
pps_hist = alt.Chart(df).mark_bar().encode(
    x=alt.X("Price_per_SqFt:Q", bin=alt.Bin(maxbins=40)),
    y="count():Q",
    tooltip=["count():Q"]
).properties(title="Price per SqFt Distribution")

st.altair_chart(pps_hist, width='stretch')

# ================= BIVARIATE ANALYSIS =================
st.header("Bivariate Analysis")

# Size vs Price Scatter
scatter = alt.Chart(df).mark_circle(size=60, opacity=0.4).encode(
    x=alt.X("Size_in_SqFt:Q", title="Size (SqFt)"),
    y=alt.Y("Price_in_Lakhs:Q", title="Price (Lakhs)"),
    tooltip=["Size_in_SqFt:Q", "Price_in_Lakhs:Q", "City:N"]
).interactive().properties(title="Size vs Price")

st.altair_chart(scatter, width='stretch')

# Avg Price by City
if "City" in df.columns:
    city_avg = (
        df.groupby("City", as_index=False)["Price_in_Lakhs"]
        .mean()
        .sort_values("Price_in_Lakhs", ascending=False)
        .head(10)
    )

    city_bar = alt.Chart(city_avg).mark_bar().encode(
        x=alt.X("City:N", sort="-y"),
        y="Price_in_Lakhs:Q",
        tooltip=["City:N", "Price_in_Lakhs:Q"]
    ).properties(title="Average Property Price by City (Top 10)")

    st.altair_chart(city_bar, width='stretch')

# Price per SqFt by Property Type
if "Property_Type" in df.columns:
    box = alt.Chart(df).mark_boxplot().encode(
        x=alt.X("Property_Type:N", title="Property Type"),
        y=alt.Y("Price_per_SqFt:Q", title="Price per SqFt"),
        tooltip=["Property_Type:N"]
    ).properties(title="Price per SqFt by Property Type")

    st.altair_chart(box, width='stretch')

# ================= CORRELATION =================
st.header("Correlation (Hover Heatmap)")

corr_df = (
    df.select_dtypes(include=np.number)
      .corr()
      .stack()
      .reset_index()
)
corr_df.columns = ["Feature 1", "Feature 2", "Correlation"]

heatmap = alt.Chart(corr_df).mark_rect().encode(
    x="Feature 1:N",
    y="Feature 2:N",
    color=alt.Color("Correlation:Q", scale=alt.Scale(scheme="redblue")),
    tooltip=["Feature 1", "Feature 2", "Correlation"]
).properties(title="Correlation Heatmap")

st.altair_chart(heatmap, width='stretch')

# ================= TOP LOCALITIES =================
if "Locality" in df.columns:
    st.header("Top 10 Most Expensive Localities")

    top_local = (
        df.groupby("Locality", as_index=False)["Price_per_SqFt"]
        .mean()
        .sort_values("Price_per_SqFt", ascending=False)
        .head(10)
    )

    local_bar = alt.Chart(top_local).mark_bar().encode(
        x=alt.X("Locality:N", sort="-y"),
        y="Price_per_SqFt:Q",
        tooltip=["Locality:N", "Price_per_SqFt:Q"]
    ).properties(title="Top 10 Expensive Localities (Price/SqFt)")

    st.altair_chart(local_bar, width='stretch')

# ---------------- DONE ----------------
st.success("EDA Completed Successfully")